#pragma once

#include <vector>
#include <unordered_map>
#include <iostream>
#include <memory>
#include <typeindex>
#include <typeinfo>
#include <type_traits>
#include <cassert>
#include <random>
#include <queue>
#include <chrono>
#include <iterator>
#include <functional>
#include <format>
#include <sstream>
#include <bitset>
#include <filesystem>